### ISSUE TITLE
BUG: .get(label) should default to empty dict

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/mdaviz#106]
This code can generate `AttributeError: 'NoneType' object has no attribute 'get'`: https://github.com/BCDA-APS/mdaviz/blob/6de0662f8bda6a3a04c7c564f14df098cc8c29ba/mdaviz/chartview.py#L188-L189

In both of these cases, the call to `.get()` should have an empty `{}` as the (default) second argument.

**Comment by rodolakis** [comment]
Done: 1b7bc351085257e65ea7a91d4026fd210e003bfd
