### ISSUE TITLE
Consistent name for classes

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#12]
MDAFolderTableModel vs mdaFolderTableView?

**Comment by prjemian** [comment]
[Python Naming Guidelines](https://peps.python.org/pep-0008/#naming-conventions) can answer this.  [Classes start with capital letter and are camel-cased](https://pythonguides.com/python-naming-conventions/).  Abbreviations in the name are no so consistent.  Either MDAFolderTableModel or MdaFolderTableModel are compliant with pep8.  Be consistent.  [pylint](https://pylint.org/) may have an opinion.
