### ISSUE TITLE
Fix errors in `f_xrdlib.py`

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#147]
<img width="772" alt="image" src="https://github.com/BCDA-APS/mdaviz/assets/39918069/678d6a26-ac88-4ff9-95e5-cde81b95d579">

**Comment by rodolakis** [comment]
This file was not converted to from python 2 to python 3.

**Comment by prjemian** [comment]
Is this file necessary?

**Comment by rodolakis** [comment]
I do not know, I thought you kept it for a reason.
Can I just delete it?

**Comment by prjemian** [comment]
@timmooney is the f_xdrlib.py file necessary?

**Comment by rodolakis** [comment]
@ravescovi helped me converted it to python3. It does not show any errors now.
