### ISSUE TITLE
Limit the checked box to one per column / row

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#31]
We can start with just 1 box per column, and eventually allow more than one for the `y` column.

**Comment by prjemian** [comment]
Should prevent multiple sections of X and also multiple checkboxes on a single signal:

![image](https://github.com/BCDA-APS/mdaviz/assets/2279984/f8415f09-4e83-42e3-8b56-56ff184c4ee7)

**Comment by prjemian** [comment]
See https://github.com/BCDA-APS/mdaviz/pull/29#pullrequestreview-1618897367
