### ISSUE TITLE
Plot from multiple scans

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#39]
At the moment, we can plot from multiple scans by selecting scan #1 , click `Add` (red curve), select a new scan, here scan #2, click `Add` again (blue and green curve). However:
- the second scan gets plotted twice - may be related to #34
- there is no good way to track which one is which in the legend: should indicate the scan number

**Comment by prjemian** [comment]
In gemviz, I added info parentheses to differentiate.  `"(#{scan_id} {stream_name} {uid[:7]})"`.  Configuration of this is a candidate for control via user preferences.  Not yet.

**Comment by prjemian** [comment]
![image](https://github.com/BCDA-APS/mdaviz/assets/2279984/77181a02-d9ae-4ac5-8d8a-6d4321d7791b)

**Comment by prjemian** [comment]
Instead of `uid[:7]`, could be some date/time representation.

**Comment by rodolakis** [comment]
For mda this is pretty straightforward since scan number are unique within a directory.

**Comment by rodolakis** [comment]
The screen shot I meant to add:

<img width="632" alt="image" src="https://github.com/BCDA-APS/mdaviz/assets/39918069/de3102e4-77f5-494e-95e7-b1c00aa2f7f9">

**Comment by prjemian** [comment]
Let's figure out how to reposition the legend (MatPlotLib can do this automatically) so that it does not clobber plotted data.

**Comment by rodolakis** [comment]
Also, when discussing with Jessica, we thought that there could be multiple tabs in the `select_fields_table_view`:
- the first one shows the common detectors to both scans; checking one of those fields would plot it for both scans
- the second and third tabs shows scan1 and scan2, respectively; checking a field in one of those would only add the plot for this specific scan. 
At the moment the table view only shows the fields for the last scan selected (on this screen shot scan #2, as indicated in the name of the tab):

<img width="748" alt="image" src="https://github.com/BCDA-APS/mdaviz/assets/39918069/c7a211c7-4e26-4f83-9f19-287871c01adb">
