### ISSUE TITLE
reposition the legend automatically

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/mdaviz#40]
Let's figure out how to reposition the legend (MatPlotLib can do this automatically) so that it does not clobber plotted data.

_Originally posted by @prjemian in https://github.com/BCDA-APS/mdaviz/issues/39#issuecomment-1724205784_

**Comment by rodolakis** [comment]
NO longer relevant, Matplotlib does that very well.

**Comment by rodolakis** [comment]
NO longer relevant, Matplotlib does that very well.
