### ISSUE TITLE
Load data without a positioner

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#52]
```bash
Traceback (most recent call last):
  File "/home/beams22/29IDUSER/bin/mdaviz/mdaviz/mda_folder_table_model.py", line 60, in data
    return action(file)
           ^^^^^^^^^^^^
  File "/home/beams22/29IDUSER/bin/mdaviz/mdaviz/mda_folder_table_model.py", line 24, in <lambda>
    "Positioner": lambda file: self.get_file_pos(file),
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams22/29IDUSER/bin/mdaviz/mdaviz/mda_folder_table_model.py", line 99, in get_file_pos
    pv = utils.byte2str(readMDA(str(filepath))[1].p[0].name)
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by rodolakis** [comment]
This error occurs over and over since `get_file_pos` is called by `mda_folder_table_model.py` for the table view.

**Comment by rodolakis** [comment]
Loading fixed by commit 31dd2cf.

Next error when trying to plot:

```bash
(mdaviz) [clueless ~/bin/mdaviz] mdaviz
Settings are saved in: /home/beams/29IDUSER/.config/BCDA-APS/mdaviz.ini
Application started ...
Folder path: '/net/s29data/export/data_29idc/2023_1/Kawasaki/mda'
Selected file: ARPES_0004.mda
Could not find a positioner or detector to plot.
```

**Comment by rodolakis** [comment]
``` bash
(mdaviz) iMac:mdaviz fannysimoes$ mdaviz &
[1] 61986
(mdaviz) iMac:mdaviz fannysimoes$ Settings are saved in: /Users/fannysimoes/.config/BCDA-APS/mdaviz.ini
Application started ...
Folder path: '/Users/fannysimoes/src/mdaviz/mdaviz/data'
Folder path: '/Users/fannysimoes/src/mdaviz/mdaviz/data/test_no_positioner'
Selected file: ARPES_0002.mda
Could not find a (positioner,detector) pair to plot.
{'Y': ['D01']}
doPlot called with action: add, args: ('add', {'Y': [0]})
doPlot called with action: replace, args: ('replace', {'Y': [0]})
```

<img width="1790" alt="image" src="https://github.com/BCDA-APS/mdaviz/assets/39918069/1d1b1dbe-ec2a-47e5-930b-be121f1948df">

**Comment by prjemian** [comment]
thought:  Could/should the positioner list always start with `index`?

**Comment by prjemian** [comment]
... for _n_-dimensional data, an index for each dimension...

**Comment by rodolakis** [comment]
Yes that is my thought. At the moment, not having P01 checked plots with index by default, but I think a P00 line by default sounds better. We can still leave the capabilities to plot vs index when no positioner is selected.

**Comment by rodolakis** [comment]
@prjemian  I want to make my P00 a scanPositioner object  (from https://github.com/EPICS-synApps/utils/blob/master/mdaPythonUtils/mda.py), so it has all the attribute of the other positioner. I feel that this would be cleaner, and that way I just create it in utils.get_det and it is done. But I can't figure out how to import the scanPOsitioner class.

**Comment by prjemian** [comment]
```py
(tiled) prjemian@arf:~/.../BCDA-APS/tiled-template$ python
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mda import scanPositioner
>>> sp = scanPositioner()
>>> print(f"{sp=}")
sp=<mda.scanPositioner object at 0x7f306fa574d0>
>>> 
```

**Comment by prjemian** [comment]
> from https://github.com/EPICS-synApps/utils/blob/master/mdaPythonUtils/mda.py

_FYI_: That repo was archived in 2022 and is now read-only.  It has been replaced here: https://github.com/EPICS-synApps/support/blob/master/utils/mdaPythonUtils/mda.py

**Comment by prjemian** [comment]
The pip install command above uses the new location.

**Comment by rodolakis** [comment]
OK I will update the env.yml with the new link.

And I was using the wrong import: `mdalib` instead of `mda`. Confused the name of the package with the name of the module (is a `mda` a module?)

**Comment by prjemian** [comment]
Yes

**Comment by prjemian** [comment]
The line for your `env.yml` file should look like this line from our tiled template:
https://github.com/BCDA-APS/tiled-template/blob/main/environment.yml#L35

**Comment by prjemian** [comment]
Looks like it may be there already.

**Comment by rodolakis** [comment]
ok

**Comment by rodolakis** [comment]
I wasn't working without the quote with the previous link.
