### ISSUE TITLE
Impossible to compare data from different directory 

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#61]
At the moment changing directory refresh the app

**Comment by rodolakis** [comment]
This also means we might want to be able to indicate from which directory a specific curve comes from (in the legend?)

**Comment by rodolakis** [comment]
Maybe we can have the option to either switch to a different directory vs open another directory. The new directory could go in a second tab in the folder table view. It could be label folder 1, folder2 to avoid very long name?

**Comment by prjemian** [comment]
Only if the legend includes data from two different directories.  Could this get verbose quickly?

**Comment by prjemian** [comment]
Is this essential for the v1.0 release?

**Comment by rodolakis** [comment]
@apsIEX  says yes, she needs to be able to compare graph from different directories. 
Note that auto-replace is the default when starting the app, but when switching directories, keep the mode the same as it was before switching.
