### ISSUE TITLE
fix "GoNext" button

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#93]
Since PR #91, pushing the `GoNext` button (and likely other similar button)  to select next file crashes the app:

```python
Traceback (most recent call last):
  File "/home/beams3/RODOLAKIS/src/mdaviz/mdaviz/mda_folder.py", line 205, in goToNext
    self.highlightNewFile(i.row())
  File "/home/beams3/RODOLAKIS/src/mdaviz/mdaviz/mda_folder.py", line 163, in highlightNewFile
    self.selectionModel().select(
RuntimeError: wrapped C/C++ object of type QItemSelectionModel has been deleted
Aborted (core dumped)
```

**Comment by prjemian** [comment]
Youch!

**Comment by prjemian** [comment]
How to reproduce this error?

**Comment by prjemian** [comment]
Want to know what are the inputs to the Qt call: https://github.com/BCDA-APS/mdaviz/blob/6b15fe0a1f60d23c893d65999dee3ad42b56477e/mdaviz/mda_folder.py#L162-L165

**Comment by prjemian** [comment]
Unfortunately, the exception handling for Qt code is troublesome.  Qt comes from a compiled library.  If that code errors, it is not possible for Python to catch the error.

**Comment by rodolakis** [comment]
I had that this morning during our demo, but now it seems to work just fine.

**Comment by rodolakis** [comment]
> Want to know what are the inputs to the Qt call:
> 
> [mdaviz/mdaviz/mda_folder.py](https://github.com/BCDA-APS/mdaviz/blob/6b15fe0a1f60d23c893d65999dee3ad42b56477e/mdaviz/mda_folder.py#L162-L165)
> 
> Lines 162 to 165 in [6b15fe0](/BCDA-APS/mdaviz/commit/6b15fe0a1f60d23c893d65999dee3ad42b56477e)
> 
>  index = self.mda_folder_tableview.tableView.model().index(row, 0) 
>  self.selectionModel().select( 
>      index, QItemSelectionModel.ClearAndSelect | QItemSelectionModel.Rows 
>  )

@prjemian  I am not sure to understand your question here

**Comment by prjemian** [comment]
Same here. In this view:
![image](https://github.com/BCDA-APS/mdaviz/assets/2279984/f2a66842-ce9a-456a-956f-e6f866b98f9a)

this button?
![image](https://github.com/BCDA-APS/mdaviz/assets/2279984/a7f9cb65-4fb5-4309-95b5-b592054c4831)

**Comment by prjemian** [comment]
If not seeing now, could consider closing.  Instead, leave open a couple days, just in case.

**Comment by rodolakis** [comment]
Yes this button.

**Comment by rodolakis** [comment]
Still not able to reproduce this crash, but the highlight of the file & automatic scroll when using the button does not appear to work anymore. It does plot the next/previous/first/last scan when the button is push, only the highlight/focus/scroll is off. 

To be investigated

**Comment by rodolakis** [comment]
After merging PR #99 and #102:
- go to first: works for plotting, but relevant file is not highlighted / focused
- go to last: works for plotting, but relevant file is not highlighted / focused
- go back 1: works for plotting, but relevant file is not highlighted / focused
- for next 1: does not work at all
